baseurl = "https://jimbo-tsai.github.io/jimbot/"
copyright = "Jimmy Tsai ©"

enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[languages.en]
title = "Jimmy Tsai"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "galleries"
name = "Galleries"
url = "/galleries/"
weight = 15





[[languages.en.menu.main]]
identifier = "films"
name = "Films"
url = "/films/"
weight = 20

[[languages.en.menu.main]]
identifier = "drawings"
name = "Drawings"
url = "/drawings/"
weight = 21

[[languages.en.menu.main]]
identifier = "paintings"
name = "Paintings"
url = "/paintings/"
weight = 22


[[languages.en.menu.main]]
identifier = "aboutme"
name = "About"
url = "/aboutme/"
weight = 11






[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.will-faught]
default = true
email = "will.faught@example.com"
name = "Will Faught"
url = "https://willfaught.com/paige"

[params.paige]
# site_title = "Jimmy Tsai"
# site_description = "Jimmy Tsai"
color = "#f3a400" # Bootstrap primary color and theme color for Safari and Windows
color_scheme = "light" # Must be "auto", "dark", or "light"
external_link_new_tab = false # Open external links in new tabs
math = false # Enable math typesetting
style = "" # CSS included at the end of the stylesheet, before style-last.css

[params.paige.git]
commit_url = "https://github.com/jimbo-tsai/jimbot/commit/%s"

[[params.paige.feed.atom.authors]]
email = "will.faught@example.com"
name = "Will Faught"
url = "https://willfaught.com/paige"

[params.paige.feed.rss]
managing_editor = "will.faught@example.com (Will Faught)"
web_master = "will.faught@example.com (Will Faught)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/jimbo-tsai/jimbot/edit/main/site/content/%s"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
